name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"
    
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build # Remove or modify this step as needed
      run: |
        composer install --ignore-platform-req=php --no-dev # doesn't work due to php 8 incompatibilites in some packages
        grunt
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        dry-run: false
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: commonsbooking # optional, remove if GitHub repo name matches SVN slug, including capitalization
